/**
 * Imports the three legal markdown sources from the PRIVATE app repo (read-only: `git show origin/main:<path>`)
 * into `src/seed/legal/{privacy,terms,support}.md`. Run: pnpm import:legal
 *
 * Rules (docs/spec/06-legal-pages.md section 1):
 * - privacy: everything above the first whole-line `---` is the internal review block and is never imported.
 * - Backticks around {{KEY}} tokens are removed (they only protected placeholders in the source).
 * - The leading `# Title` is dropped (the route renders the title); privacy gets the effective/updated/version lines.
 * - Internal identifiers (table, column, setting and bucket names in backticks) are removed from the public text.
 * - Fails loudly if any internal marker survives. Exported pure functions are unit-tested.
 */
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const PRIVATE_REPO =
  process.env.STUMPNOTE_APP_REPO ?? '/Users/nilesh93/Projects/personal/stumpnote'

export const FORBIDDEN: Array<[string, RegExp]> = [
  ['project ref', /csuknuuneuuyepqfgkgy/i],
  ['issue number', /(^|[\s(])(GH\s*)?#\d{2,}/],
  ['source path', /\b(lib|supabase|ios|android|docs|scripts)\/[\w./-]+/],
  ['code file', /\.(dart|sql|swift|kt|ts|sh)\b/],
  [
    'review block',
    /DRAFT FOR LEGAL REVIEW|Review block|Legal-review checklist|Verified facts this draft/i,
  ],
  ['backticked identifier', /`[a-z]+_[a-z_]+`|`(audio|clips|mindset-audio|profiles)`/],
]

/** Text after the first whole-line `---`. Table rows like `|---|---|` do not match. */
export function stripReviewBlock(src: string): string {
  const lines = src.split('\n')
  const i = lines.findIndex((l) => /^---\s*$/.test(l))
  if (i === -1) throw new Error('privacy source: no whole-line --- separator found')
  return lines.slice(i + 1).join('\n')
}

export function dropLeadingTitle(body: string): string {
  return body.replace(/^\s*# [^\n]*\n+/, '')
}

export function unwrapTokens(body: string): string {
  return body.replace(/`(\{\{[^}`]+\}\})`/g, '$1')
}

/** Remove internal identifiers (table, column, setting, bucket names) from public text. */
export function scrubIdentifiers(body: string): string {
  return (
    body
      // " (`share_health_with_ai`)" style parentheticals, and parentheticals made only of backticked names
      .replace(/ \((`[^`]+`(, )?)+\)/g, '')
      // parentheticals that mix backticked names with plain words, e.g. "(`audio`)" or "(`clips`, screenshots)"
      .replace(/ \([^)]*`[^)]*\)/g, '')
      // "Supabase Auth and `profiles`" / "`profiles`, `guardian_players`" / "Supabase `device_push_tokens`"
      .replace(/ and `[^`]+`/g, '')
      .replace(/, `[^`]+`/g, '')
      .replace(/ `[a-z][a-z_-]+`(?=[ |.,;)])/g, '')
      .replace(/`[a-z][a-z_-]+`/g, '')
      // a table cell emptied by the scrub falls back to the generic store
      .replace(/\| \| /g, '| Supabase Postgres | ')
      .replace(/session summary in \|/g, 'session summary in Supabase |')
  )
}

export function leaks(text: string): string[] {
  return FORBIDDEN.filter(([, re]) => re.test(text)).map(([name]) => name)
}

export function normalise(slug: 'privacy' | 'terms' | 'support', src: string): string {
  let body = slug === 'privacy' ? stripReviewBlock(src) : src
  body = unwrapTokens(dropLeadingTitle(body))
  body = scrubIdentifiers(body)
  if (slug === 'privacy') {
    body =
      '**Effective date:** {{EFFECTIVE_DATE}}  \n**Last updated:** {{LAST_UPDATED}}  \n**Policy version:** {{POLICY_VERSION}}\n\n' +
      body.replace(/^\s+/, '')
  }
  return body.trimEnd() + '\n'
}

const SOURCES = {
  privacy: 'docs/PRIVACY_POLICY.md',
  terms: 'docs/TERMS_OF_USE.md',
  support: 'docs/SUPPORT.md',
} as const

export const LEGAL_SLUGS = [
  'privacy',
  'terms',
  'support',
  'cookies',
  'account-deletion',
  'data-safety',
] as const

const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'src', 'seed', 'legal')

/** The markdown files are the reviewable source; `bodies.ts` is generated from them so the bodies ship in the server bundle. */
export function writeBundle(): void {
  const bodies: Record<string, string> = {}
  for (const slug of LEGAL_SLUGS) {
    const file = path.join(OUT, `${slug}.md`)
    if (!existsSync(file)) throw new Error(`missing ${file}`)
    bodies[slug] = readFileSync(file, 'utf8')
  }
  const header =
    '// GENERATED by scripts/import-legal.ts (pnpm import:legal / pnpm legal:bundle) from the sibling .md files. Do not edit.\n'
  writeFileSync(
    path.join(OUT, 'bodies.ts'),
    `${header}export const legalBodies = ${JSON.stringify(bodies, null, 2)} as const\n`,
  )
  console.log(`bundle: ${LEGAL_SLUGS.length} bodies`)
}

function main() {
  mkdirSync(OUT, { recursive: true })
  if (process.argv.includes('--bundle')) return writeBundle()
  execFileSync('git', ['-C', PRIVATE_REPO, 'fetch', '-q', 'origin'])
  for (const [slug, file] of Object.entries(SOURCES) as Array<[keyof typeof SOURCES, string]>) {
    const src = execFileSync('git', ['-C', PRIVATE_REPO, 'show', `origin/main:${file}`], {
      encoding: 'utf8',
      maxBuffer: 10_000_000,
    })
    const body = normalise(slug, src)
    const bad = leaks(body)
    if (bad.length)
      throw new Error(`${slug}: internal content survived the import (${bad.join(', ')})`)
    writeFileSync(path.join(OUT, `${slug}.md`), body)
    console.log(
      `${slug}: ${body.split('\n').length} lines, ${(body.match(/\{\{/g) ?? []).length} tokens`,
    )
  }
  writeBundle()
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) main()
