/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    features: Feature;
    personas: Persona;
    posts: Post;
    'changelog-entries': ChangelogEntry;
    faqs: Faq;
    testimonials: Testimonial;
    'legal-pages': LegalPage;
    media: Media;
    users: User;
    'waitlist-signups': WaitlistSignup;
    'audit-log': AuditLog;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    personas: PersonasSelect<false> | PersonasSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'changelog-entries': ChangelogEntriesSelect<false> | ChangelogEntriesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'waitlist-signups': WaitlistSignupsSelect<false> | WaitlistSignupsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'beta-access': BetaAccess;
    'legal-values': LegalValue;
    'analytics-settings': AnalyticsSetting;
    'price-scenarios': PriceScenario;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'beta-access': BetaAccessSelect<false> | BetaAccessSelect<true>;
    'legal-values': LegalValuesSelect<false> | LegalValuesSelect<true>;
    'analytics-settings': AnalyticsSettingsSelect<false> | AnalyticsSettingsSelect<true>;
    'price-scenarios': PriceScenariosSelect<false> | PriceScenariosSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL segment. Auto-generated from the title when empty.
   */
  slug: string;
  /**
   * Sets the page accent (data-persona).
   */
  persona?: ('player' | 'coach' | 'parent' | 'team' | 'none') | null;
  showInNav?: boolean | null;
  /**
   * Forced on for legal pages in notice mode.
   */
  noindex?: boolean | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * Screenshots must use the fictional demo data only.
   */
  isSynthetic?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  title: string;
  /**
   * URL segment. Auto-generated from the title when empty.
   */
  slug: string;
  area: 'journal-memory' | 'mental-game' | 'game-day' | 'team' | 'coach' | 'parent' | 'platform';
  status: 'available-web' | 'in-beta' | 'preview' | 'coming-soon';
  benefit?: string | null;
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas".
 */
export interface Persona {
  id: number;
  title: string;
  /**
   * URL segment. Auto-generated from the title when empty.
   */
  slug: string;
  accent?: ('player' | 'coach' | 'parent' | 'team') | null;
  headline?: string | null;
  leadWith?: ('default' | 'consent') | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL segment. Auto-generated from the title when empty.
   */
  slug: string;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "changelog-entries".
 */
export interface ChangelogEntry {
  id: number;
  title: string;
  date: string;
  app?: ('player' | 'coach' | 'parent' | 'web' | 'site')[] | null;
  kind?: ('new' | 'improved' | 'fixed') | null;
  publicStatus?: ('in-beta' | 'available-web') | null;
  /**
   * Never reference internal issue numbers.
   */
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('general' | 'availability' | 'privacy' | 'pricing' | 'team' | 'coach' | 'parent' | 'support') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  attribution: string;
  role?: string | null;
  consentGiven: boolean;
  permissionDate: string;
  /**
   * Disclosure of any material connection. Juniors: note guardian consent.
   */
  materialConnection?: string | null;
  /**
   * Admin only.
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  slug: 'privacy' | 'terms' | 'support' | 'cookies' | 'account-deletion' | 'data-safety';
  title: string;
  /**
   * Markdown with {{KEY}} placeholders, stored verbatim.
   */
  body?: string | null;
  effectiveDate?: string | null;
  lastUpdated?: string | null;
  policyVersion?: string | null;
  reviewStatus?: ('draft' | 'lawyer-reviewed') | null;
  /**
   * Internal. Never rendered.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admin: everything incl. analytics. Editor: content. Viewer: read-only.
   */
  roles: ('admin' | 'editor' | 'viewer')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-signups".
 */
export interface WaitlistSignup {
  id: number;
  email: string;
  persona?: ('player' | 'captain' | 'coach' | 'parent' | 'other') | null;
  consent: boolean;
  /**
   * Exact consent line shown to the visitor.
   */
  consentText: string;
  /**
   * Page path the form was submitted from.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  user?: (number | null) | User;
  action: string;
  panel?: string | null;
  range?: string | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'personas';
        value: number | Persona;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'changelog-entries';
        value: number | ChangelogEntry;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'waitlist-signups';
        value: number | WaitlistSignup;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  persona?: T;
  showInNav?: T;
  noindex?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  area?: T;
  status?: T;
  benefit?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas_select".
 */
export interface PersonasSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  accent?: T;
  headline?: T;
  leadWith?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "changelog-entries_select".
 */
export interface ChangelogEntriesSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  app?: T;
  kind?: T;
  publicStatus?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  role?: T;
  consentGiven?: T;
  permissionDate?: T;
  materialConnection?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  body?: T;
  effectiveDate?: T;
  lastUpdated?: T;
  policyVersion?: T;
  reviewStatus?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  isSynthetic?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-signups_select".
 */
export interface WaitlistSignupsSelect<T extends boolean = true> {
  email?: T;
  persona?: T;
  consent?: T;
  consentText?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  panel?: T;
  range?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Public, non-secret site configuration. Read by server components only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  webAppUrl?: string | null;
  /**
   * Indicative pricing, no buy button (D-14).
   */
  showPricing?: boolean | null;
  showTrialLine?: boolean | null;
  footerDisclosure?: string | null;
  /**
   * No legal entity named until the owner confirms it.
   */
  copyrightLine?: string | null;
  motionDefault?: ('auto' | 'reduced') | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerItems?:
    | {
        label: string;
        /**
         * Path (/features) or full URL.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  headerCta?: {
    label?: string | null;
    /**
     * Path (/features) or full URL.
     */
    url?: string | null;
  };
  footerColumns?:
    | {
        heading: string;
        items?:
          | {
              label: string;
              /**
               * Path (/features) or full URL.
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The Apple standard EULA link is added automatically by the footer.
   */
  footerLegalItems?:
    | {
        label: string;
        /**
         * Path (/features) or full URL.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Drives every beta call to action. No App Store claims until the apps are live.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beta-access".
 */
export interface BetaAccess {
  id: number;
  state: 'waitlist' | 'testflight' | 'appstore';
  /**
   * Ships OFF. Turn on only once /privacy is live (not in notice mode) and a deletion/unsubscribe contact exists.
   */
  waitlistEnabled?: boolean | null;
  testflightUrl?: string | null;
  appStoreUrl?: {
    player?: string | null;
    coach?: string | null;
    parent?: string | null;
  };
  /**
   * The exact consent sentence stored with each signup.
   */
  waitlistConsentText?: string | null;
  waitlistSuccessMessage?: string | null;
  comingSoonLine?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Legal placeholder values. Empty values stay visible as notices on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-values".
 */
export interface LegalValue {
  id: number;
  COMPANY_LEGAL_NAME?: string | null;
  COMPANY_ABN?: string | null;
  COMPANY_ADDRESS?: string | null;
  PRIVACY_CONTACT_EMAIL?: string | null;
  SUPPORT_EMAIL?: string | null;
  GOVERNING_LAW?: string | null;
  EFFECTIVE_DATE?: string | null;
  LAST_UPDATED?: string | null;
  POLICY_VERSION?: string | null;
  RETENTION_PERIOD?: string | null;
  BACKUP_PURGE_DAYS?: string | null;
  USAGE_LOG_RETENTION?: string | null;
  DELETE_ACCOUNT_PATH?: string | null;
  LEGAL_REVIEW?: string | null;
  DPO_OR_REPRESENTATIVE?: string | null;
  LEGAL_REVIEW_DONE?: ('' | 'yes') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Admin analytics configuration. No secrets are stored here (env only).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings".
 */
export interface AnalyticsSetting {
  id: number;
  provider?: ('none' | 'posthog' | 'plausible' | 'nouance-plugin') | null;
  defaultRange?: ('7d' | '30d' | '90d') | null;
  fixturesBanner?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-scenarios".
 */
export interface PriceScenario {
  id: number;
  scenarios?:
    | {
        label: string;
        appliesToModelPattern?: string | null;
        inputPerMillionUsd?: number | null;
        outputPerMillionUsd?: number | null;
        cachedPerMillionUsd?: number | null;
        audioInputPerMillionUsd?: number | null;
        ttsPerMillionCharsUsd?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  webAppUrl?: T;
  showPricing?: T;
  showTrialLine?: T;
  footerDisclosure?: T;
  copyrightLine?: T;
  motionDefault?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  footerLegalItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beta-access_select".
 */
export interface BetaAccessSelect<T extends boolean = true> {
  state?: T;
  waitlistEnabled?: T;
  testflightUrl?: T;
  appStoreUrl?:
    | T
    | {
        player?: T;
        coach?: T;
        parent?: T;
      };
  waitlistConsentText?: T;
  waitlistSuccessMessage?: T;
  comingSoonLine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-values_select".
 */
export interface LegalValuesSelect<T extends boolean = true> {
  COMPANY_LEGAL_NAME?: T;
  COMPANY_ABN?: T;
  COMPANY_ADDRESS?: T;
  PRIVACY_CONTACT_EMAIL?: T;
  SUPPORT_EMAIL?: T;
  GOVERNING_LAW?: T;
  EFFECTIVE_DATE?: T;
  LAST_UPDATED?: T;
  POLICY_VERSION?: T;
  RETENTION_PERIOD?: T;
  BACKUP_PURGE_DAYS?: T;
  USAGE_LOG_RETENTION?: T;
  DELETE_ACCOUNT_PATH?: T;
  LEGAL_REVIEW?: T;
  DPO_OR_REPRESENTATIVE?: T;
  LEGAL_REVIEW_DONE?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings_select".
 */
export interface AnalyticsSettingsSelect<T extends boolean = true> {
  provider?: T;
  defaultRange?: T;
  fixturesBanner?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-scenarios_select".
 */
export interface PriceScenariosSelect<T extends boolean = true> {
  scenarios?:
    | T
    | {
        label?: T;
        appliesToModelPattern?: T;
        inputPerMillionUsd?: T;
        outputPerMillionUsd?: T;
        cachedPerMillionUsd?: T;
        audioInputPerMillionUsd?: T;
        ttsPerMillionCharsUsd?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}